server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:matgo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  security:
    jwt:
      secret: ${JWT_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    directory: ${AWS_S3_DIRECTORY}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/matgo-api.yaml
    path: /docs/swagger

images:
  default-profile-image: ${AWS_S3_DEFAULT_PROFILE_IMAGE}

external:
  jeonju-restaurant:
    url: ${JEONJU_RESTAURANT_URL}
    key: ${JEONJU_RESTAURANT_KEY}

logging:
  level:
    org.hibernate.type.descriptor.sql: info