openapi: 3.0.1
info:
  title: matgo-API
  description: matgo-API입니다
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/member:
    put:
      tags:
      - Member
      summary: 회원 정보 수정
      description: 회원 정보 수정
      operationId: 회원 정보 수정
      responses:
        "204":
          description: "204"
      security:
      - bearerAuthJWT: []
  /api/auth/login:
    post:
      tags:
      - Auth
      summary: 로그인
      description: 로그인
      operationId: 로그인
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-auth-login-1354847443'
            examples:
              로그인:
                value: |-
                  {
                    "email" : "test@naver.com",
                    "password" : "1!asdasd",
                    "role" : "ROLE_USER"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-member-signup486549215'
              examples:
                로그인:
                  value: |-
                    {
                      "accessToken" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcwMzQwNjM4NSwiaXNzIjoibWF0Z28iLCJleHAiOjE3MDM0MDY0NDV9.s6XcEgQvBR65mq3jXdfl2syxUhRz4vgIr0nK29v_WPg"
                    }
  /api/auth/logout:
    delete:
      tags:
      - Auth
      summary: 로그아웃
      description: 로그아웃
      operationId: 로그아웃
      responses:
        "204":
          description: "204"
      security:
      - bearerAuthJWT: []
  /api/auth/send-temporary-password:
    post:
      tags:
      - Auth
      summary: 임시 비밀번호 발급
      description: 임시 비밀번호 발급
      operationId: 임시 비밀번호 발급
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-auth-send-temporary-password-272417006'
            examples:
              임시 비밀번호 발급:
                value: |-
                  {
                    "email" : "test@naver.com"
                  }
      responses:
        "204":
          description: "204"
  /api/auth/verify-emailcode:
    post:
      tags:
      - Auth
      summary: 이메일 인증
      description: 이메일 인증
      operationId: 이메일 인증
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-auth-verify-emailcode358504075'
            examples:
              이메일 인증:
                value: |-
                  {
                    "email" : "test@naver.com",
                    "code" : "123456"
                  }
      responses:
        "204":
          description: "204"
  /api/member/reset-password:
    put:
      tags:
      - Member
      summary: 비밀번호 초기화
      description: 비밀번호 초기화
      operationId: 비밀번호 초기화
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-member-reset-password-244801712'
            examples:
              비밀번호 초기화:
                value: |-
                  {
                    "currentPassword" : "1!asdasd",
                    "newPassword" : "1!qweqwe"
                  }
      responses:
        "204":
          description: "204"
      security:
      - bearerAuthJWT: []
  /api/member/signup:
    post:
      tags:
      - Member
      summary: 회원가입
      description: 회원가입
      operationId: 회원가입
      responses:
        "201":
          description: "201"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-member-signup486549215'
              examples:
                회원가입:
                  value: signup@naver.com
components:
  schemas:
    api-auth-send-temporary-password-272417006:
      type: object
      properties:
        email:
          type: string
          description: 이메일
    api-auth-login-1354847443:
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        role:
          type: string
          description: 유저 권한
        email:
          type: string
          description: 이메일
    api-auth-verify-emailcode358504075:
      type: object
      properties:
        code:
          type: string
          description: 인증 코드
        email:
          type: string
          description: 이메일
    api-member-reset-password-244801712:
      type: object
      properties:
        newPassword:
          type: string
          description: 새 비밀번호
        currentPassword:
          type: string
          description: 현재 비밀번호
    api-member-signup486549215:
      type: object
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
